// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sportive.API.Data;

#nullable disable

namespace Sportive.API.Migrations.MasterDb
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20260623083408_AddDynamicSubscriptions")]
    partial class AddDynamicSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sportive.API.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxBranches")
                        .HasColumnType("int");

                    b.Property<int>("MaxStorageGB")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Free trial plan",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = false,
                            MaxBranches = 1,
                            MaxStorageGB = 1,
                            MaxUsers = 3,
                            MonthlyPrice = 0m,
                            Name = "Trial",
                            YearlyPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Essential features for small teams",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = false,
                            MaxBranches = 2,
                            MaxStorageGB = 10,
                            MaxUsers = 10,
                            MonthlyPrice = 29m,
                            Name = "Basic",
                            YearlyPrice = 290m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Advanced features for growing businesses",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = true,
                            MaxBranches = 10,
                            MaxStorageGB = 100,
                            MaxUsers = 50,
                            MonthlyPrice = 99m,
                            Name = "Pro",
                            YearlyPrice = 990m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Unlimited capabilities for large organizations",
                            DisplayOrder = 4,
                            IsActive = true,
                            IsFeatured = false,
                            MaxBranches = -1,
                            MaxStorageGB = -1,
                            MaxUsers = -1,
                            MonthlyPrice = 299m,
                            Name = "Enterprise",
                            YearlyPrice = 2990m
                        });
                });

            modelBuilder.Entity("Sportive.API.Models.Tenant", b =>
                {
                    b.Property<Guid>("TenantGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DatabasePassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DatabaseUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TenantGuid");

                    b.HasIndex("DatabaseName")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Sportive.API.Models.TenantSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TenantGuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantGuid");

                    b.ToTable("TenantSubscriptions");
                });

            modelBuilder.Entity("Sportive.API.Models.TenantUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("StorageUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantGuid");

                    b.ToTable("TenantUsages");
                });

            modelBuilder.Entity("Sportive.API.Models.TenantSubscription", b =>
                {
                    b.HasOne("Sportive.API.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sportive.API.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Sportive.API.Models.TenantUsage", b =>
                {
                    b.HasOne("Sportive.API.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
